pipeline {
    agent {dockerfile True}
    
    stages {
        stage('Build') {
            steps {
                script {
                    // Install Node.js dependencies
                    sh 'npm install node'
                    sh 'npm install express'
                }
            }
        }
        
      
        }
    }
}
