pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                script {
                    // Install Node.js dependencies
                    sh 'npm install node'
                    sh 'npm install express'
                }
            }
        }
            stage('Package') {
            steps {
                script {
                    // Package the Node.js application
                    sh 'npm run build'
                }
            }
        }
      
  stage('Dockerize') {
            steps {
                script {
                    // Build Docker image
                    
                    sh 'docker build -t filthyspartan/miniproject .'
                }
            }
        }
        
        stage('Push to DockerHub') {
            steps {
                script {
                    // Push Docker image to DockerHub
                  
                        sh "docker login -u $filthyspartan -p $GitBastard1!"
                        sh 'docker push filthyspartan/miniproject .'
                    
                }
            }
        }

}
}
